// Generated by @solidjs/vite-plugin (start.env) — do not edit.
// Regenerated on every dev server and build start from env.ts.
// Keep this file (and the schema) inside your tsconfig "include".

declare module 'virtual:env/client' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
  };
  export { env };
  export default env;
}

declare module 'virtual:env/server' {
  type __Schema = typeof import("./env")['default'];
  type __Out<T> = T extends { '~standard': { types?: { output: infer O } | undefined } }
    ? O
    : string;
  const env: {
    readonly "SYMAPI_URL": __Out<__Schema["server"]["SYMAPI_URL"]>;
    readonly "POSTGRES_USER": __Out<__Schema["server"]["POSTGRES_USER"]>;
    readonly "POSTGRES_PASSWORD": __Out<__Schema["server"]["POSTGRES_PASSWORD"]>;
    readonly "POSTGRES_DB": __Out<__Schema["server"]["POSTGRES_DB"]>;
    readonly "DATABASE_URL": __Out<__Schema["server"]["DATABASE_URL"]>;
    readonly "BETTER_AUTH_URL": __Out<__Schema["server"]["BETTER_AUTH_URL"]>;
    readonly "BETTER_AUTH_SECRET": __Out<__Schema["server"]["BETTER_AUTH_SECRET"]>;
    readonly "MICROSOFT_CLIENT_ID": __Out<__Schema["server"]["MICROSOFT_CLIENT_ID"]>;
    readonly "MICROSOFT_CLIENT_SECRET": __Out<__Schema["server"]["MICROSOFT_CLIENT_SECRET"]>;
    readonly "MICROSOFT_TENANT_ID": __Out<__Schema["server"]["MICROSOFT_TENANT_ID"]>;
  };
  export { env };
  export default env;
}
