services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./db-data/:/var/lib/postgresql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
